### ISSUE TITLE
Group Presentation - Kanban Setup

### ISSUE THREAD

**Issue by MarcoAurelioAntonio** [MarcoAurelioAntonio/Global-Academy-Client#13]
#### This is our Set up project for the full stack app.
- Our members are:
     - @NelsonAraujo93 
     - @kensteph 
     - @biruk-bereka 
     - @MarcoAurelioAntonio 

- [This is the Server Side of the Kanban project](https://github.com/users/MarcoAurelioAntonio/projects/7)
- [This is the Client Side of our Kanban project](https://github.com/users/MarcoAurelioAntonio/projects/8)

- These are the repositories links for the front end and the back end:
     [Client](https://github.com/MarcoAurelioAntonio/Appointment-Client-Side)
     [Server](https://github.com/MarcoAurelioAntonio/Appointment-Server-Side)

#### Server Kanban Board:
<img width="1346" alt="Screenshot 2023-06-08 at 10 13 17 AM" src="https://github.com/MarcoAurelioAntonio/Appointment-Client-Side/assets/29135748/b1021ecc-23ae-43a3-a02f-d3a970ecf458">
 
#### Client Kanban Board:
![image](https://github.com/MarcoAurelioAntonio/Appointment-Client-Side/assets/99001924/6275aee0-1692-4c5b-a98e-4cfc739b1f21)

**Comment by Meltrust** [comment]
Hi @NelsonAraujo93,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, are assigned, and pointings are equal ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
